### ISSUE TITLE
zap-full-scan.py

### ISSUE THREAD

**Issue by 92username** [92username/desafio-lacrei-saude-devops#2]
![image](https://github.com/user-attachments/assets/be229e93-2fdd-457e-9e8d-8f0cead1857e)

analyze and fix this issue.

**Comment by 92username** [comment]
fixed

**Comment by 92username** [comment]
now we are stucked here: 
```
2024-12-28 15:06:53,773 I/O error: [Errno 13] Permission denied: '/zap/wrk/zap_report.html'
Traceback (most recent call last):
Total of 4 URLs
  File "/zap/zap-full-scan.py", line 469, in main
    write_report(os.path.join(base_dir, report_html), zap.core.htmlreport())
  File "/zap/zap_common.py", line 569, in write_report
    with open(file_path, mode='wb') as f:
PermissionError: [Errno 13] Permission denied: '/zap/wrk/zap_report.html' 
```

```
ERROR [Errno 13] Permission denied: '/zap/wrk/zap_report.html'
Error: Process completed with exit code 3.
```

check next permissions required on container.

**Comment by 92username** [comment]
fixed.

``` ERROR [Errno 13] Permission denied: '/zap/wrk/zap_report.html' Error: Process completed with exit code 3. ```

docker container name was mistaken on docker hub.
